# Generated by Django 2.0.7 on 2019-06-04 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BikeReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='bike',
            name='model',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='seats',
        ),
        migrations.AddField(
            model_name='bike',
            name='current_owner',
            field=models.CharField(default='None', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='parking_name',
            field=models.CharField(default='NDK', max_length=256),
        ),
        migrations.AddField(
            model_name='bike',
            name='reservator',
            field=models.CharField(default='None', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bikereservation',
            name='bike_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.Bike'),
        ),
        migrations.AddField(
            model_name='bikereservation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bikerent',
            name='bike_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.Bike'),
        ),
        migrations.AddField(
            model_name='bikerent',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
